### ISSUE TITLE
模型返回打印是空串

### ISSUE THREAD

**Issue by LeqsNaN** [doublewinter0/xfyun-xinghuo#2]
您好，
按照您在readme里面给的使用，我照样使用您给的代码来实验，发现星火返回的结果是空的？没内容....您看看问题出在哪啊 (我对爬虫和网络通信这方面懂的不多🥹)。
我用的python版本是3.9.16。所以我改了match method那部分的代码成if else判断了。
然后print了一下登录和__stream返回的resp。登录应该是没问题的吧？代码和返回结果如下：
<img width="487" alt="image" src="https://github.com/doublewinter0/xfyun-xinghuo/assets/49872515/7dd3a6c3-7bed-42a1-8c8a-a01b69d54ccc">
![image](https://github.com/doublewinter0/xfyun-xinghuo/assets/49872515/cacec76c-68ba-4248-9a68-1d0a1b4c9c3f)

**Comment by doublewinter0** [comment]
出现 `data: [belongerr]` 应该是 `chat_id` 参数不正确，你可以调用 `get_chat_list()` 函数获取会话列表。

**Comment by doublewinter0** [comment]
> 您好， 按照您在readme里面给的使用，我照样使用您给的代码来实验，发现星火返回的结果是空的？没内容....您看看问题出在哪啊 (我对爬虫和网络通信这方面懂的不多🥹)。 我用的python版本是3.9.16。所以我改了match method那部分的代码成if else判断了。 然后print了一下登录和__stream返回的resp。登录应该是没问题的吧？代码和返回结果如下： <img alt="image" width="487" src="https://user-images.githubusercontent.com/49872515/244923279-7dd3a6c3-7bed-42a1-8c8a-a01b69d54ccc.png"> <img alt="image" width="1238" src="https://user-images.githubusercontent.com/49872515/244923300-972cdca9-376c-4a64-9c5b-63a8eaa35a4d.png">

**建议把登录返回结果的关键部分打码处理一下，避免被别人非法利用。**

**Comment by LeqsNaN** [comment]
感谢🙏，
修改了 chat_id 之后，打印 line 是这样的：
<img width="516" alt="image" src="https://github.com/doublewinter0/xfyun-xinghuo/assets/49872515/5be93c7e-0bca-4ef1-98e9-9ec48e03ea83">
但是，最后输出还是没东西...👀

**Comment by doublewinter0** [comment]
每一行 `data: xxxx` 就是返回的 *base64* 数据流，API 会将该数据流解码并返回，你再看一下。

**Comment by LeqsNaN** [comment]
解决了，谢谢大佬🙏。
我这里是需要在 line 上加一个 strip...可能是返回的东西上有换行符之类的？我用的是Ubuntu. 不同的操作系统会对这个有影响么👀
<img width="606" alt="image" src="https://github.com/doublewinter0/xfyun-xinghuo/assets/49872515/0891dd2b-d962-405f-955b-7944ca0377a1">

**Comment by doublewinter0** [comment]
应该和操作系统没有关系，我也是 Linux 。这里的代码可能需要优化一下，欢迎提交 PR。

**Comment by LeqsNaN** [comment]
一个新的异常，就是用create_chat_list()创建新的对话时，会报以下错误，大佬您再看看？
<img width="1221" alt="image" src="https://github.com/doublewinter0/xfyun-xinghuo/assets/49872515/269a4138-e7b7-453e-b16a-361ffafcb0d9">

**Comment by doublewinter0** [comment]
> 一个新的异常，就是用create_chat_list()创建新的对话时，会报以下错误，大佬您再看看？ <img alt="image" width="1221" src="https://user-images.githubusercontent.com/49872515/245007127-269a4138-e7b7-453e-b16a-361ffafcb0d9.png">

bug 已修复，你再试试！
