### ISSUE TITLE
你那些环境变量能设置在一个文件里吗？

### ISSUE THREAD

**Issue by iliaokun** [doublewinter0/xfyun-xinghuo#3]
这样代码显得方便点。  我用的window系统哟。 难得配置文件。

**Comment by doublewinter0** [comment]
由于我的环境几乎是 *Linux* 和 *Docker*，所以目前只提供了环境变量的形式，这样能让代码看起来更简洁一些。如果把这些配置项放到一个文件里边，就需要先读取这些值，这样的写法不如前面的优雅；加上 *Docker* 这些容器化技术，设置环境变量往往是首选。

如果你是在 *Windows* 平台下开发调试的话，可以在 *IDE* 中设置这些环境变量，只需要设置一次。

后期我会考虑在代码初始化中加入这些配置项，这样就可以更加灵活地初始化相关代码块。
