### ISSUE TITLE
奇怪的对话

### ISSUE THREAD

**Issue by yushangxiao** [doublewinter0/xfyun-xinghuo#4]
调用本项目后，
去看在官网的对话记录:
看起来是一直在使用“重新生成”的功能，但它是不同的问题。<好像很容易被发现偷用的样子>
在get_chat_history的返回值中，也只有一次对话。其中消息的属性中有"brotherIds"的列表存储了“重新生成”的其他对话id。
这导致即使是同一个会话，它是没有记忆的。
![屏幕截图(28)](https://github.com/doublewinter0/xfyun-xinghuo/assets/104288245/39635e68-5ccc-4928-8511-6fd47359efb6)
![屏幕截图(29)](https://github.com/doublewinter0/xfyun-xinghuo/assets/104288245/8b5952af-763a-4044-beb8-13532f90c9b0)
两个图片是点击右上方"左右标签"切换的结果
主要代码:
async def run(pro):
    global bot
    bot = ChatBot('foo')
    bot.login()
    ses_id=await get_session_id(pro)# 获取ses_id
    if ses_id==0:
        return "删除成功"
    res=await bot.chat(ses_id, pro, bot.gt_token) 
    print(await bot.get_chat_history(ses_id))
    return res
如果有什么错误，请指正我。期待您的回复。

**Comment by yushangxiao** [comment]
通过抓包已经找到原因了。
chat的接口有个新参数，sid：表示上一条机器人消息的sid。
在不传它时，被认为是会话的第一条消息。
非会话第一条消息应当在chat接口中传入sid。
sid可以从会话记录中找到最后一条消息（机器人消息），从它的的属性的sid中提取。
这样就解决了。

**Comment by doublewinter0** [comment]
> 通过抓包已经找到原因了。 chat的接口有个新参数，sid：表示上一条机器人消息的sid。 在不传它时，被认为是会话的第一条消息。 非会话第一条消息应当在chat接口中传入sid。 sid可以从会话记录中找到最后一条消息（机器人消息），从它的的属性的sid中提取。 这样就解决了。

非常感谢！可以提个 **PR** 吗？
